# NOTE: This workflow assumes a Unix-based runner (Linux/macOS) since it relies
# on Bash scripts and `chmod` for execution.

name: Run Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: "Test App"
      UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}

    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Pretty self-explanatory: give execute permission to runner 
      - name: Make scripts executable
        run: |
          chmod +x build.sh
          chmod +x upload.sh
        
      # CLI call to simulated build process
      - name: Run Build
        run: |
          ./build.sh --platform Android --project-name "$APP_NAME"

      # CLI call to simulated upload process
      - name: Upload
        run: |
          ./upload.sh android "build/Android/$APP_NAME.apk"